### ISSUE TITLE
sharing weights

### ISSUE THREAD

**Issue by BlackTrade** [Lednik7/nto-ai-text-recognition#1]
If it possible, could I ask you to share weights model of Detection 2 - SEGM_MODEL_PATH = "model_final 17k 2160 3130.pth"

**Comment by Lednik7** [comment]
Download weights from [yandex disk](https://storage.yandexcloud.net/datasouls-ods/submissions/e7c3d807-0f20-4003-9935-977432b4d615/14eafde9/sub_8%281%29.zip)
